### ISSUE TITLE
easy way to validate json and print in same format we use

### ISSUE THREAD

**Issue by kurtseifried** [cloudsecurityalliance/gsd-tools#11]
python3 -m json.tool defaults to indent=4 and there isn't any way to set it to indent=2 (there is in newer versions perhaps but I don't have an up to date version apparently). 

```
#!/usr/bin/env python3

import sys
import json
from tempfile import mkstemp
import os
import shutil

filename = sys.argv[1]

with open(filename, 'r') as filehandle:
      try:
            json_data = json.load(filehandle)
      except:
            print("Your JSON is broken, reloading to spit the error out\n\n")
            data = json.load(filehandle)
            quit()
            
      json_output = json.dumps(json_data, indent=2)
      json_output = json_output.rstrip("\n")
      file_descriptor, path = mkstemp()
      with open(path, 'w') as f:
            f.write(json_output)
      os.close(file_descriptor)
      shutil.move(path, filename)
```

I don't see any problems here,

**Comment by joshbressers** [comment]
I moved this to the gsd-tools repo

json.tool 3.9 allows you to specify whitespace, and since @raphaelahrens pasted that jq command from let's just suggest that. Humans should not be touching this data (I understand they have to at the moment because we need better tools), I don't want to encourage bad behavior
